### ISSUE TITLE
Create August 22 Quarterly report

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/link2care_public#25]
# Overview

2022-08-09, from James:

Hi Brad,
The data session minutes and arrest data has been updated in teams. Can you create the quarterly agenda for the next quarterly meeting?
Arrests data is under Current_Arrest_Data.
Quarterly Meeting
·       8/19/22 at 11am

## Left off at

Finished an initial draft. Combining Table 3 and Table 4.

## Task list

- [x] Update file paths in create_quarterly_report.Rmd to OneDrive.
- [x] Fill in the table
- [ ] Make improvements to the tables and code
