### ISSUE TITLE
Merge QDS data files in SPSS

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/link2care_public#32]
# Overview

On 2023-02-27, Brad and Sangeeta were going over the code for creating the merged survey data. Perhaps the most complex part of this code is the processing and merging the QDS data (including REDCap). The files that are most relevant to that process are [data_survey_01_qds_import.Rmd](https://github.com/brad-cannell/link2care_public/blob/master/data_survey_01_qds_import.Rmd) and [data_survey_02_redcap_import.Rmd](https://github.com/brad-cannell/link2care_public/blob/master/data_survey_02_redcap_import.Rmd).

Because the QDS and REDCap data are exported in SPSS format, because there is SPSS code already written to calculate summary scores for all of the scales used in this data, and because Sangeeta is more comfortable with SPSS than R at this point, we decided to do the following processes in SPSS.

1. Calculate summary scores for all scale measures used in QDS and REDCap.
2. Rename all the variables so that they match the names we are currently using in R.
3. Merge the data from all 5 visits and REDCap into a single dataset.
4. Add variable labels to the merged data.
5. Add value labels to the merged data.6. Save the merged data so that it can be imported into R and merged with the other relevant datasets. 

After this is done, we will import the merged QDS/REDCap file using a new version of [data_survey_01_qds_import.Rmd](https://github.com/brad-cannell/link2care_public/blob/master/data_survey_01_qds_import.Rmd). The new version will replace the current [data_survey_01_qds_import.Rmd](https://github.com/brad-cannell/link2care_public/blob/master/data_survey_01_qds_import.Rmd) and [data_survey_02_redcap_import.Rmd](https://github.com/brad-cannell/link2care_public/blob/master/data_survey_02_redcap_import.Rmd) files. Hopefully, the rest of the merge sequence will work without the need for much modification. 

After we have all the data merged, we will create a codebook (#10)

# Tasks

- [ ] Calculate summary scores for all scale measures used in QDS and REDCap.
- [ ] Rename all the variables so that they match the names we are currently using in R.
- [ ] Merge the data from all 5 visits and REDCap into a single dataset.
- [ ] Add variable labels to the merged data.
- [ ] Add value labels to the merged data.
- [ ] Save the merged data so that it can be imported into R and merged with the other relevant datasets.

**Comment by mbcann01** [comment]
On 2023-03-10, we decided not to do this anymore because Sangeeta did not want to rename all of the variables in SPSS. We are just going to use the R data import files.
