### ISSUE TITLE
Update the wiki

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/link2care_public#60]
# Overview

Update the wiki so that a new GRA should be able to walk in off the street and begin contributing in a fairly short amount of time without having to ask the research team a ton of questions.

I want the documentation to answer these questions
- Where do I get the data?
- Where do I get the codebook?
- How do I update the data and codebook?
- What if I just want to analyze the combined data without modifying it?

I think the answers to these questions should exist in
- The GitHub README
- The GitHub Wiki
- The codebook
- The SharePoint

# Tasks (core)

- [x] Clone the wiki locally and turn it into an R Project.
- [x] Add a sidebar to the wiki.
- [x] Add notes on Morri's file changes to the Wiki.
- [x] Delete unneeded files from the repo.
- [x] Test lintr and styler
- [x] Change the data set name in the codebook from `combined_data` to `combined_participant_data`.
- [x] Link to the codebook in the wiki. The codebook doesn't have to be totally finalized yet. for the sake of time, just link a basic codebook and then fix the description, etc. later.
- [x] Change "You" language to "We" language" on the wiki homepage.
- [x] Describe how to use/update `retrieve_data_stats.R`. It looks like we may need to update the variable name list when we make changes.
- [x] Consider breaking the homepage up into separate pages. If you do this, update the links on the wiki homepage.
- [x] Determine if the `Column Names` page is still necessary and accurate.
- [x] Determine if the `Data Cleaning` page is still necessary and accurate.
- [x] Update the GitHub README
- [x] Update the SharePoint (if needed).
- [x] Send data and codebook to Michael and Jenn.

**Comment by mbcann01** [comment]
2024-02-08:
- Adding notes about what each of the files does to the [wiki home page](https://github.com/brad-cannell/link2care_public/wiki). 
- As part of that process, I cloned a copy of the repo to my desktop. I'm making sure the files are described accurately and work as expected.

**Comment by mbcann01** [comment]
2024-02-12:
- Adding notes about what each of the files does to the [wiki home page](https://github.com/brad-cannell/link2care_public/wiki).
- As part of that process, I'm running all of the qmd files to make sure they are described accurately and work as expected.
- Left off at running through data_survey_04_caclulating.qmd. Pick up at the beginning of data_survey_05_post_processing.
Here are some copy and paste notes to help with commits:

For wiki, just keep amending the previous commit

````

brad-cannell/link2care_public#60

Update data_survey_03_combining.qmd
- Don’t load the entire tidyverse package.
- Remove the check for the data file’s last modified date. It wasn’t helpful.
- Changed the name of the “Combined Participant Data” folder to “combined_participant_data” 
- Updated data checks to use retrieve_data_stats.R
````

**Comment by mbcann01** [comment]
2024-02-14

I got a little bit off track yesterday with too may tangentially related tasks. So, I split the task list above into "core" tasks and "other" tasks. Today, I'm working on core tasks to stay on track for the Friday deadline. I can work on other tasks later (or turn them into separate issues).

- I created a new codebook that we can link to in the wiki.
